class Problem29:
    TITLE = 'Distinct powers'
    DESCRIPTION = 'How many distinct terms are in the sequence generated by a**b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?'

    def answer(self) -> int:
        distinct_terms = set()

        for a in range(2, 101):
            for b in range(2, 101):
                distinct_terms.add(a ** b)

        return len(distinct_terms)
