class Problem2:
    TITLE = 'Even Fibonacci number'
    DESCRIPTION = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. \n" \
                  " By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... \n " \
                  "By considering the terms in the Fibonacci sequence whose values do not exceed four million,\n" \
                  " find the sum of the even-valued terms."

    def answer(self) -> int:
        sum_even_valued_terms = 0

        fib_n_1, fib_n = 1, 2
        new_fib = 2

        while fib_n < 4_000_000:
            if new_fib % 2 == 0:
                sum_even_valued_terms += new_fib

            new_fib = fib_n_1 + fib_n
            fib_n_1, fib_n = fib_n, new_fib

        return sum_even_valued_terms
